import { Inter } from "next/font/google";
import "@/app/styles/globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="nav_wrapper">
        <div className="nav_container">
        <div className="logo"></div>
          
          <div className="nav_items">
            <a href="/">Home</a>
            <a href="/docs">Docs</a>
          </div>
        </div>
        </div>
        {children}</body>
    </html>
  );
}
