import { Inter } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="nav_a">
          <div className="nav_b">
            <a href="/">Home</a>
            <a href="/docs">Docs</a>
          </div>
        </div>
        {children}</body>
    </html>
  );
}
